name: kotlinx_dart_converter
description: A json converter for Kotlinx to Dart
version: 1.0.1
homepage: http://www.cachet.dk
author: thomasnilsson <tnni@dtu.dk>

environment:
  sdk: '>=2.0.0-dev.66.0 <2.0.0'

dev_dependencies:
  test: ^1.0.0
